# docker-compose.yml
version: '3.8'

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./sentiment-analysis-frontend
      dockerfile: Dockerfile
      # This 'args' block now reads variables from the root .env file
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    # The root .env file is automatically used for the runtime environment,
    # so the env_file directive is no longer needed here.
    networks:
      - sentiment-net
    depends_on:
      - backend
    restart: unless-stopped

  # Backend Service (Go + SGX)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env.backend
    networks:
      - sentiment-net
    restart: unless-stopped

# Defines the network that allows services to communicate
networks:
  sentiment-net:
    driver: bridge
