#include <openenclave/host.h>
#include <stdio.h>
#include <stdlib.h> // For exit, EXIT_FAILURE

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h" // Will be generated in the build directory

// This is the function that the enclave will call back into to
// print a message.
void host_helloworld()
{
    fprintf(stdout, "Enclave called into host to print: Hello World!\n");
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    if (argc != 2 && argc !=3) // Adjusted to allow for --simulate
    {
        fprintf(stderr, "Usage: %s enclave_image_path [--simulate]\n", argv[0]);
        goto exit;
    }

    uint32_t enclave_flags = OE_ENCLAVE_FLAG_DEBUG;
    if (argc == 3 && strcmp(argv[2], "--simulate") == 0)
    {
        fprintf(stdout, "[Host] Running in SIMULATION mode.\n");
        enclave_flags |= OE_ENCLAVE_FLAG_SIMULATE;
    } else {
        fprintf(stdout, "[Host] Running in SGX HARDWARE mode (or default).\n");
    }


    // Create the enclave by calling oeedger8r generated function.
    // The function name oe_create_helloworld_enclave is derived from the EDL filename.
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, enclave_flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(stderr, "Failed to create enclave: oe_create_helloworld_enclave(): result=%u (%s)\n", result, oe_result_str(result));
        goto exit;
    }
    fprintf(stdout, "[Host] Enclave created successfully.\n");

    // Call into the enclave
    fprintf(stdout, "[Host] Calling into enclave_helloworld().\n");
    result = enclave_helloworld(enclave);
    if (result != OE_OK)
    {
        fprintf(stderr, "[Host] Calling into enclave_helloworld failed: result=%u (%s)\n", result, oe_result_str(result));
        goto exit;
    }
    fprintf(stdout, "[Host] enclave_helloworld() call successful.\n");

    ret = 0;

exit:
    //Clean up the enclave if we created one
    if (enclave)
    {
        fprintf(stdout, "[Host] Terminating enclave.\n");
        oe_terminate_enclave(enclave);
    }

    return ret;
}